### ISSUE TITLE
Garbled output from Raspberry Pi 4B

### ISSUE THREAD

**Issue by nickpwhite** [eleclab-rpi/8INCH_HDMI_1280X720#2]
Hi there,

I'm trying to install a Raspberry Pi 4B with this display, and the display looks like this when I boot it up. I was hoping you could help me troubleshoot this issue.

![PXL_20231114_014451722 MP](https://github.com/eleclab-rpi/8INCH_HDMI_1280X720/assets/8175555/ec76f2c6-4353-4f2d-a31b-fabd733e2e60)

Thank you!

**Comment by eleclab-rpi** [comment]
HI, dear user, are you using an 8" 1280x720 HDMI display?
Please try the new display firmware, please refer to the pdf document to operate, it is very simple and only requires a tweezers and USB cable.
https://github.com/eleclab-rpi/Display_Firmware

Are you using buster or bullseye? Please refer to the following modifications to config.txt:
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=87

hdmi_ignore_edid=0xa5000080
hdmi_cvt 1280 720 60 3 0 0 0

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes 1:DVI 2:HDMI(with audio)
hdmi_drive=2

Best Wishes!



***@***.***
 
From: Nick White
Date: 2023-11-14 13:52
To: eleclab-rpi/8INCH_HDMI_1280X720
CC: Subscribed
Subject: [eleclab-rpi/8INCH_HDMI_1280X720] Garbled output from Raspberry Pi 4B (Issue #2)
Hi there,
I'm trying to install a Raspberry Pi 4B with this display, and the display looks like this when I boot it up. I was hoping you could help me troubleshoot this issue.
Thank you!

**Comment by nickpwhite** [comment]
Hi, thanks for your response! I am using an 7.4" 1280x400 HDMI display. I am using Raspberry Pi OS (Legacy, 64-bit) based on bullseye. This is the relevant section of my config.txt
```
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=87

hdmi_ignore_edid=0xa5000080
hdmi_cvt=1280 720 60 3 0 0 0

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
hdmi_drive=2
```

I tried to do the firmware upgrade on the display, but ran into some issues. The program said that I successfully installed the driver to my PC, but when I plug the display into my PC and run ArteryISPProgrammer.exe, I don't see any devices listed in the USB DFU table. I believe I shorted the pin correctly, as my multimeter reports continuity between the specified pins. I'm not sure that the driver actually installed, because I don't see any device in Device Manager called "AT32 Bootloader DFU".

I am very new to microcontrollers and working with this kind of hardware, so I apologize if there's something obvious I'm missing! Thanks again.

**Comment by nickpwhite** [comment]
I have a video of the boot sequence. It briefly displays the boot logo before it starts flickering.
https://github.com/eleclab-rpi/8INCH_HDMI_1280X720/assets/8175555/450d9f03-aec4-4cbd-a461-ff883fe4510b

**Comment by nickpwhite** [comment]
I just realized that the board on the display says 7.4" 1280x400, but the materials and instructions are all for the 8" 1280x720 model. I've updated my /boot/config.txt using [this guide](https://github.com/eleclab-rpi/7INCH4_HDMI_1280x400/blob/main/ElecLab%207.4%E2%80%9D%20DSI%20Touchscreen%20Display%20USER%20GUIDE.pdf), the current values are:
```
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=87

hdmi_ignore_edid=0xa5000080
hdmi_timings=1280 0 64 2 18 400 0 10 3 42 0 0 0 60 0 37330000 3

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
hdmi_drive=1
```

I didn't actually receive the analog audio output cable, so I couldn't install that one, but otherwise I followed the instructions in the proper guide and am still seeing the issue. The boot sequence changed, it seems as if it's showing 2 displays, one on the top half of the screen and one on the bottom half, it's also slightly distorted, but still readable. Any advice?

**Comment by eleclab-rpi** [comment]
HI, Dear user, Sorry for the delay, here's what to do when upgrading firmware:

1. Use a USB Type-c cable to connect the 5V+Touch interface of the display to the computer.

2. Pull the USB Touch switch of the display PCB to the PC position, so that the USB signal of the display will be transmitted to the 5V+Touch socket.

Another question is are you using an 8" 1280x720 display or a 7.4" 1280x400 bar display? The parameters of the two of them will be different: hdmi_cvt=1280 720 60 3 0 0 0
hdmi_drive=2

hdmi_timings=1280 0 64 2 18 400 0 10 3 42 0 0 0 60 0 37330000 3
hdmi_drive=1

Good Luck!




***@***.***
 
From: Nick White
Date: 2023-11-15 15:03
To: eleclab-rpi/8INCH_HDMI_1280X720
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/8INCH_HDMI_1280X720] Garbled output from Raspberry Pi 4B (Issue #2)
Hi, thanks for your response! I am using an 7.4" 1280x400 HDMI display. I am using Raspberry Pi OS (Legacy, 64-bit) based on bullseye. This is the relevant section of my config.txt
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1
# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=87
hdmi_ignore_edid=0xa5000080
hdmi_cvt=1280 720 60 3 0 0 0
# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
hdmi_drive=2

I tried to do the firmware upgrade on the display, but ran into some issues. The program said that I successfully installed the driver to my PC, but when I plug the display into my PC and run ArteryISPProgrammer.exe, I don't see any devices listed in the USB DFU table. I believe I shorted the pin correctly, as my multimeter reports continuity between the specified pins. I'm not sure that the driver actually installed, because I don't see any device in Device Manager called "AT32 Bootloader DFU".
I am very new to microcontrollers and working with this kind of hardware, so I apologize if there's something obvious I'm missing! Thanks again.

**Comment by eleclab-rpi** [comment]
The video confirmed that it is indeed an 8" 1280x720 display, so just use the following parameters:
hdmi_cvt=1280 720 60 3 0 0 0
hdmi_drive=2



***@***.***
 
From: Nick White
Date: 2023-11-15 15:39
To: eleclab-rpi/8INCH_HDMI_1280X720
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/8INCH_HDMI_1280X720] Garbled output from Raspberry Pi 4B (Issue #2)
I have a video of the boot sequence. It briefly displays the boot logo before it starts flickering.
https://github.com/eleclab-rpi/8INCH_HDMI_1280X720/assets/8175555/450d9f03-aec4-4cbd-a461-ff883fe4510b

**Comment by eleclab-rpi** [comment]
It is true that the 8" display screen borrows a 7.4" 1280x400 PCB board, but the firmware uses an 8" 1280x720 one. What is a bit strange is why it starts normally but becomes abnormal after entering the desktop.

Please try this and observe the display:
1. Lift the Raspberry Pi off the display.
2. Use a USB Type-c cable to connect the Raspberry Pi USB 3.0 and the 5V+Touch interface of the display.
3. Use an HDMI cable to connect the HDMI port of the Raspberry Pi and the HDMI port of the display.
4. Connect the Raspberry Pi to a 5V power supply.



***@***.***
 
From: Nick White
Date: 2023-11-15 23:53
To: eleclab-rpi/8INCH_HDMI_1280X720
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/8INCH_HDMI_1280X720] Garbled output from Raspberry Pi 4B (Issue #2)
I just realized that the board on the display says 7.4" 1280x400, but the materials and instructions are all for the 8" 1280x720 model. I've updated my /boot/config.txt using this guide, the current values are:
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1
# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=87
hdmi_ignore_edid=0xa5000080
hdmi_timings=1280 0 64 2 18 400 0 10 3 42 0 0 0 60 0 37330000 3
# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
hdmi_drive=1

I didn't actually receive the analog audio output cable, so I couldn't install that one, but otherwise I followed the instructions in the proper guide and am still seeing the issue. The boot sequence changed, it seems as if it's showing 2 displays, one on the top half of the screen and one on the bottom half, it's also slightly distorted, but still readable. Any advice?

**Comment by nickpwhite** [comment]
>Please try this and observe the display:
>1. Lift the Raspberry Pi off the display.
>2. Use a USB Type-c cable to connect the Raspberry Pi USB 3.0 and the 5V+Touch interface of the display.
>3. Use an HDMI cable to connect the HDMI port of the Raspberry Pi and the HDMI port of the display.
>4. Connect the Raspberry Pi to a 5V power supply.

When I do this, the display flashes on for a second, still glitchy, and then turns off. I have a video here:
https://github.com/eleclab-rpi/8INCH_HDMI_1280X720/assets/8175555/b3e8a904-ac38-4196-991b-e00cd385da0a

I think the pi, the port, and my cable are okay, I'm able to plug it into an external monitor via the HDMI cable with no issue.

When attempting to upgrade firmware using your instructions, the device shows up in Device Manager as "USB Input Device" under "Human Interface Devices" instead of showing as "AT32 Bootloader DFU" under "Other Devices" like the documentation says it should. Furthermore, when I try to install the driver automatically with the tool or manually via Device Manager it still does not show in ArteryISPProgrammer.exe.
![Screenshot 2023-11-15 215925](https://github.com/eleclab-rpi/8INCH_HDMI_1280X720/assets/8175555/79a2424b-a56b-4a5d-95f5-1521ee0e9de4)

Do you have any other guidance?

**Comment by eleclab-rpi** [comment]
So let's upgrade a firmware first. If the computer detects the USB input device, it should be that the MCU of the display is not in DFU mode. Please refer to the following steps. The main thing is to use tweezers to short-circuit the boot pin when the power is turned off, and then power it on to boot from USB.



***@***.***
 
From: Nick White
Date: 2023-11-16 14:46
To: eleclab-rpi/8INCH_HDMI_1280X720
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/8INCH_HDMI_1280X720] Garbled output from Raspberry Pi 4B (Issue #2)
Please try this and observe the display:
Lift the Raspberry Pi off the display.
Use a USB Type-c cable to connect the Raspberry Pi USB 3.0 and the 5V+Touch interface of the display.
Use an HDMI cable to connect the HDMI port of the Raspberry Pi and the HDMI port of the display.
Connect the Raspberry Pi to a 5V power supply.
When I do this, the display flashes on for a second, still glitchy, and then turns off. I have a video here:
https://github.com/eleclab-rpi/8INCH_HDMI_1280X720/assets/8175555/b3e8a904-ac38-4196-991b-e00cd385da0a
I think the pi, the port, and my cable are okay, I'm able to plug it into an external monitor via the HDMI cable with no issue.
When attempting to upgrade firmware using your instructions, the device shows up in Device Manager as "USB Input Device" under "Human Interface Devices" instead of showing as "AT32 Bootloader DFU" under "Other Devices" like the documentation says it should. Furthermore, when I try to install the driver automatically with the tool or manually via Device Manager it still does not show in ArteryISPProgrammer.exe.
Do you have any other guidance?
